# Generated by Django 5.2.3 on 2025-06-16 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_company_companydetails_copyprice_costdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='clients.client'),
        ),
    ]
