# Generated by Django 5.2.3 on 2025-06-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_company_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceselection',
            options={'verbose_name': 'Service Selection', 'verbose_name_plural': 'Service Selections'},
        ),
        migrations.RemoveField(
            model_name='serviceselection',
            name='selected_services',
        ),
        migrations.AddField(
            model_name='serviceselection',
            name='packages',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='serviceselection',
            name='company_id',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('services', models.ManyToManyField(to='clients.service')),
            ],
        ),
    ]
