# Generated by Django 5.2.3 on 2025-06-17 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_serviceselection_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='client',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='company',
        ),
        migrations.RemoveField(
            model_name='servicedetails',
            name='company',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='costdetails',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='costsummary',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='estimation',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='package',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='serviceselection',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='testdata',
            name='company_id',
        ),
        migrations.AddField(
            model_name='camp',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camps', to='clients.client'),
        ),
        migrations.AddField(
            model_name='client',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='costdetails',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_details', to='clients.client'),
        ),
        migrations.AddField(
            model_name='costsummary',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_summaries', to='clients.client'),
        ),
        migrations.AddField(
            model_name='estimation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimations', to='clients.client'),
        ),
        migrations.AddField(
            model_name='package',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='clients.client'),
        ),
        migrations.AddField(
            model_name='servicedetails',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_details', to='clients.client'),
        ),
        migrations.AddField(
            model_name='serviceselection',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_selections', to='clients.client'),
        ),
        migrations.AddField(
            model_name='testdata',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_data', to='clients.client'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CompanyDetails',
        ),
    ]
