# Generated by Django 5.2.3 on 2025-06-17 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_company_client_remove_camp_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='package',
            name='services',
            field=models.ManyToManyField(related_name='packages', to='clients.service'),
        ),
    ]
