# Generated by Django 5.2.3 on 2025-06-19 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_groups_client_is_active_client_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.package'),
        ),
    ]
