# Generated by Django 5.2.3 on 2025-06-20 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_testdata_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='report_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.testtype'),
        ),
        migrations.AddField(
            model_name='testdata',
            name='report_type_cost',
            field=models.IntegerField(default=0),
        ),
    ]
