# Generated by Django 5.2.3 on 2025-06-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_testdata_report_type_testdata_report_type_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='pan_card',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
