# Generated by Django 5.2.3 on 2025-06-27 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_client_client_id_alter_client_gst_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='clients.camp'),
        ),
    ]
