# Generated by Django 5.2.3 on 2025-06-27 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_package_camp'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceselection',
            name='camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_selections', to='clients.camp'),
        ),
    ]
