# Generated by Django 5.2.3 on 2025-07-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_serviceselection_camp'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='login_type',
            field=models.CharField(choices=[('Client', 'Client'), ('Coordinator', 'Coordinator')], default='Client', max_length=20),
        ),
    ]
