# Generated by Django 5.2.3 on 2025-07-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_client_login_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='Unknown Name', max_length=255),
            preserve_default=False,
        ),
    ]
