# Generated by Django 5.2.3 on 2025-07-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_alter_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='ready_to_go',
            field=models.BooleanField(default=False),
        ),
    ]
