# Generated by Django 5.2.4 on 2025-07-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clients', '0015_camp_ready_to_go'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this client belongs to.', related_name='client_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='client',
            name='login_type',
            field=models.CharField(choices=[('Client', 'Client'), ('Coordinator', 'Coordinator'), ('Technician', 'Technician')], default='Client', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this client.', related_name='client_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
