# Generated by Django 5.2.4 on 2025-07-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_alter_client_groups_alter_client_login_type_and_more'),
        ('technician', '0002_technicianserviceassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='technicians',
            field=models.ManyToManyField(blank=True, related_name='assigned_packages', to='technician.technician'),
        ),
    ]
