# Generated by Django 5.2.4 on 2025-07-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_package_technicians'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='login_type',
            field=models.CharField(choices=[('Client', 'Client'), ('Coordinator', 'Coordinator'), ('Technician', 'Technician'), ('Doctor', 'Doctor')], default='Client', max_length=20),
        ),
    ]
