# Generated by Django 5.2.4 on 2025-07-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_alter_client_login_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='login_type',
            field=models.CharField(choices=[('Client', 'Client'), ('Coordinator', 'Coordinator'), ('Technician', 'Technician'), ('Doctor', 'Doctor'), ('Optometrist', 'Optometrist')], default='Client', max_length=20),
        ),
    ]
