# Generated by Django 5.2.4 on 2025-07-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_alter_client_login_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
