# Generated by Django 5.2.4 on 2025-07-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_camp_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
