# Generated by Django 5.2.4 on 2025-07-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_package_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='login_type',
            field=models.CharField(choices=[('Client', 'Client'), ('Coordinator', 'Coordinator'), ('Technician', 'Technician'), ('Doctor', 'Doctor'), ('Optometrist', 'Optometrist'), ('Dentist', 'Dentist')], default='Client', max_length=20),
        ),
    ]
