# Generated by Django 5.2.4 on 2025-07-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_alter_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='login_type',
            field=models.CharField(choices=[('Client', 'Client'), ('Coordinator', 'Coordinator'), ('Technician', 'Technician'), ('Doctor', 'Doctor'), ('Optometrist', 'Optometrist'), ('Dentist', 'Dentist'), ('Audiometrist', 'Audiometrist')], default='Client', max_length=20),
        ),
    ]
