# Generated by Django 5.2.4 on 2025-07-07 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_alter_client_groups_alter_client_login_type_and_more'),
        ('technician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianServiceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.camp')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.service')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technician.technician')),
            ],
            options={
                'unique_together': {('technician', 'service', 'camp')},
            },
        ),
    ]
