# Generated by Django 5.2.4 on 2025-07-08 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_package_technicians'),
        ('technician', '0002_technicianserviceassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianserviceassignment',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.package'),
        ),
    ]
