# Generated by Django 5.2.4 on 2025-07-11 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_manager', '0005_patientdata_package'),
        ('technician', '0003_technicianserviceassignment_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_air_250', models.IntegerField(blank=True, null=True)),
                ('left_air_500', models.IntegerField(blank=True, null=True)),
                ('left_air_1000', models.IntegerField(blank=True, null=True)),
                ('left_air_2000', models.IntegerField(blank=True, null=True)),
                ('left_air_4000', models.IntegerField(blank=True, null=True)),
                ('left_air_8000', models.IntegerField(blank=True, null=True)),
                ('right_air_250', models.IntegerField(blank=True, null=True)),
                ('right_air_500', models.IntegerField(blank=True, null=True)),
                ('right_air_1000', models.IntegerField(blank=True, null=True)),
                ('right_air_2000', models.IntegerField(blank=True, null=True)),
                ('right_air_4000', models.IntegerField(blank=True, null=True)),
                ('right_air_8000', models.IntegerField(blank=True, null=True)),
                ('left_bone_250', models.IntegerField(blank=True, null=True)),
                ('left_bone_500', models.IntegerField(blank=True, null=True)),
                ('left_bone_1000', models.IntegerField(blank=True, null=True)),
                ('left_bone_2000', models.IntegerField(blank=True, null=True)),
                ('left_bone_4000', models.IntegerField(blank=True, null=True)),
                ('right_bone_250', models.IntegerField(blank=True, null=True)),
                ('right_bone_500', models.IntegerField(blank=True, null=True)),
                ('right_bone_1000', models.IntegerField(blank=True, null=True)),
                ('right_bone_2000', models.IntegerField(blank=True, null=True)),
                ('right_bone_4000', models.IntegerField(blank=True, null=True)),
                ('left_ear_finding', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Moderate-Severe', 'Moderate-Severe'), ('Severe', 'Severe'), ('Profound', 'Profound')], max_length=20, null=True)),
                ('right_ear_finding', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Moderate-Severe', 'Moderate-Severe'), ('Severe', 'Severe'), ('Profound', 'Profound')], max_length=20, null=True)),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='audiometry_reports/')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audiometry', to='camp_manager.patientdata')),
            ],
        ),
    ]
