# Generated by Django 5.2.4 on 2025-07-14 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_manager', '0005_patientdata_package'),
        ('technician', '0004_audiometry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Optometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('far_vision_right', models.CharField(blank=True, max_length=100, null=True)),
                ('far_vision_left', models.CharField(blank=True, max_length=100, null=True)),
                ('near_vision_right', models.CharField(blank=True, max_length=100, null=True)),
                ('near_vision_left', models.CharField(blank=True, max_length=100, null=True)),
                ('color_vision_normal', models.BooleanField(default=False)),
                ('color_vision_other', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='optometry_reports/')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_optometry', to='camp_manager.patientdata')),
            ],
        ),
    ]
