# Generated by Django 5.2.4 on 2025-07-15 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_manager', '0005_patientdata_package'),
        ('technician', '0006_vitals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='doctor_signatures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_medical_conditions', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('has_medications', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('medications', models.TextField(blank=True, null=True)),
                ('has_allergies', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('chief_complaint', models.TextField(blank=True, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('diagnostic_tests', models.TextField(blank=True, null=True)),
                ('advice', models.TextField(blank=True, null=True)),
                ('fitness_status', models.CharField(choices=[('FIT', 'FIT'), ('UNFIT', 'UNFIT')], max_length=10)),
                ('unfit_reason', models.TextField(blank=True, null=True)),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='consultation_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='technician.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp_manager.patientdata')),
            ],
        ),
    ]
