# Generated by Django 5.2.4 on 2025-07-16 06:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0007_doctor_doctorconsultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='optometry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
