# Generated by Django 5.2.4 on 2025-07-16 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0008_optometry_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='optometry',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optometry_reports', to='technician.doctor'),
        ),
    ]
