# Generated by Django 5.2.4 on 2025-07-16 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0010_optometrist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optometry',
            name='doctor',
        ),
        migrations.AddField(
            model_name='optometry',
            name='optometrist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optometry_reports', to='technician.optometrist'),
        ),
    ]
