# Generated by Django 5.2.4 on 2025-07-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0011_remove_optometry_doctor_optometry_optometrist'),
    ]

    operations = [
        migrations.AddField(
            model_name='optometry',
            name='add_left',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='optometry',
            name='add_right',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='optometry',
            name='axis_left',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='optometry',
            name='axis_right',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='optometry',
            name='color_vision_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optometry',
            name='cylindrical_left',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='optometry',
            name='cylindrical_right',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='optometry',
            name='spherical_left',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='optometry',
            name='spherical_right',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
