# Generated by Django 5.2.4 on 2025-07-16 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0012_optometry_add_left_optometry_add_right_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optometrist',
            name='technician',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='optometrist_profile', to='technician.technician'),
            preserve_default=False,
        ),
    ]
