# Generated by Django 5.2.4 on 2025-07-17 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0014_doctor_technician'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('service_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technician.servicestatus')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='technician.technician')),
            ],
        ),
    ]
