# Generated by Django 5.2.4 on 2025-07-17 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_manager', '0006_patientdata_test_date'),
        ('technician', '0015_servicelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiometry',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiometries', to='camp_manager.patientdata'),
        ),
    ]
