# Generated by Django 5.2.4 on 2025-07-17 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_manager', '0006_patientdata_test_date'),
        ('technician', '0016_alter_audiometry_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_date', models.DateField(blank=True, null=True)),
                ('family_diabetes', models.CharField(default='no', max_length=3)),
                ('family_diabetes_years', models.IntegerField(blank=True, null=True)),
                ('family_diabetes_relation', models.CharField(blank=True, max_length=100)),
                ('family_hypertension', models.CharField(default='no', max_length=3)),
                ('family_hypertension_years', models.IntegerField(blank=True, null=True)),
                ('family_hypertension_relation', models.CharField(blank=True, max_length=100)),
                ('family_other', models.TextField(blank=True)),
                ('medical_diabetes', models.CharField(default='no', max_length=3)),
                ('medical_diabetes_years', models.IntegerField(blank=True, null=True)),
                ('medical_hypertension', models.CharField(default='no', max_length=3)),
                ('medical_hypertension_years', models.IntegerField(blank=True, null=True)),
                ('current_medications', models.CharField(default='no', max_length=3)),
                ('medications_list', models.TextField(blank=True)),
                ('past_surgeries', models.TextField(blank=True)),
                ('pain_teeth', models.BooleanField(default=False)),
                ('pain_teeth_numbers', models.CharField(blank=True, max_length=200)),
                ('pain_regions', models.JSONField(default=dict)),
                ('pain_days', models.IntegerField(blank=True, null=True)),
                ('sensitivity', models.BooleanField(default=False)),
                ('sensitivity_cold', models.BooleanField(default=False)),
                ('sensitivity_hot', models.BooleanField(default=False)),
                ('sensitivity_sweet', models.BooleanField(default=False)),
                ('sensitivity_sour', models.BooleanField(default=False)),
                ('sensitivity_regions', models.JSONField(default=dict)),
                ('bleeding_gums', models.BooleanField(default=False)),
                ('other_complaints', models.TextField(blank=True)),
                ('dental_caries', models.BooleanField(default=False)),
                ('grossly_carious', models.CharField(blank=True, max_length=200)),
                ('pit_fissure_caries', models.CharField(blank=True, max_length=200)),
                ('other_caries', models.TextField(blank=True)),
                ('gingiva', models.BooleanField(default=False)),
                ('gingiva_condition', models.CharField(blank=True, max_length=20)),
                ('missing_teeth', models.BooleanField(default=False)),
                ('missing_teeth_numbers', models.CharField(blank=True, max_length=200)),
                ('occlusion', models.BooleanField(default=False)),
                ('occlusion_type', models.CharField(blank=True, max_length=20)),
                ('malocclusion_type', models.CharField(blank=True, max_length=20)),
                ('malocclusion_details', models.JSONField(default=dict)),
                ('other_findings', models.TextField(blank=True)),
                ('restoration_required', models.BooleanField(default=False)),
                ('restoration_teeth', models.CharField(blank=True, max_length=200)),
                ('rct_required', models.BooleanField(default=False)),
                ('rct_teeth', models.CharField(blank=True, max_length=200)),
                ('iopa_required', models.BooleanField(default=False)),
                ('iopa_teeth', models.CharField(blank=True, max_length=200)),
                ('oral_prophylaxis_required', models.BooleanField(default=False)),
                ('medications', models.TextField(blank=True)),
                ('replacement_required', models.BooleanField(default=False)),
                ('other_advice', models.TextField(blank=True)),
                ('saved_report', models.JSONField(blank=True, default=dict)),
                ('report_saved_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='dental_reports/')),
                ('pdf_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_saved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dental_consultation', to='camp_manager.patientdata')),
            ],
        ),
    ]
