# Generated by Django 5.2.4 on 2025-07-17 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0018_dentist_dentalconsultation_dentist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='email',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='name',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='password',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='technician',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technician', to=settings.AUTH_USER_MODEL),
        ),
    ]
