# Generated by Django 5.2.4 on 2025-07-19 11:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0019_remove_technician_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
