# Generated by Django 5.2.4 on 2025-07-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0021_audiometrist_audiometry_audiometrist'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='abdomen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='body_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='exhale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='inhale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='oxygen_saturation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
