# Generated by Django 5.2.4 on 2025-07-28 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_manager', '0008_identity'),
        ('technician', '0022_vitals_abdomen_vitals_body_temperature_vitals_exhale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('bp', models.CharField(blank=True, max_length=20, null=True)),
                ('pulse', models.IntegerField(blank=True, null=True)),
                ('body_temperature', models.FloatField(blank=True, null=True)),
                ('body_fat', models.FloatField(blank=True, null=True)),
                ('visceral_rate', models.FloatField(blank=True, null=True)),
                ('bmr', models.FloatField(blank=True, null=True)),
                ('muscle_mass', models.FloatField(blank=True, null=True)),
                ('muscle_rate', models.FloatField(blank=True, null=True)),
                ('skeletal_muscle', models.FloatField(blank=True, null=True)),
                ('bone_mass', models.FloatField(blank=True, null=True)),
                ('protein_rate', models.FloatField(blank=True, null=True)),
                ('protein_mass', models.FloatField(blank=True, null=True)),
                ('oxygen_saturation', models.FloatField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('lipid', models.FloatField(blank=True, null=True)),
                ('rbc', models.FloatField(blank=True, null=True)),
                ('hb', models.FloatField(blank=True, null=True)),
                ('random_blood_sugar', models.FloatField(blank=True, null=True)),
                ('creatinine', models.FloatField(blank=True, null=True)),
                ('egfr', models.FloatField(blank=True, null=True)),
                ('total_bilirubin', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pathology', to='camp_manager.patientdata')),
            ],
        ),
    ]
