# Generated by Django 5.2.4 on 2025-07-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0023_pathology'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathology',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='pathology_reports/'),
        ),
    ]
