# Generated by Django 5.2.4 on 2025-07-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0024_pathology_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathology',
            old_name='bmr',
            new_name='total_cholesterol',
        ),
        migrations.RemoveField(
            model_name='pathology',
            name='body_fat',
        ),
        migrations.RemoveField(
            model_name='pathology',
            name='body_temperature',
        ),
        migrations.RemoveField(
            model_name='pathology',
            name='bone_mass',
        ),
        migrations.RemoveField(
            model_name='pathology',
            name='bp',
        ),
        migrations.RemoveField(
            model_name='pathology',
            name='heart_rate',
        ),
        migrations.RemoveField(
            model_name='pathology',
            name='height',
        ),
        migrations.RemoveField(
            model_name='pathology',
            name='lipid',
        ),
        migrations.RemoveField(
            model_name='pathology',
            name='muscle_mass',
        ),
        migrations.RemoveField(
            model_name='pathology',
            name='muscle_rate',
        ),
        migrations.RemoveField(
            model_name='pathology',
            name='oxygen_saturation',
        ),
        migrations.RemoveField(
            model_name='pathology',
            name='protein_mass',
        ),
        migrations.RemoveField(
            model_name='pathology',
            name='protein_rate',
        ),
        migrations.RemoveField(
            model_name='pathology',
            name='pulse',
        ),
        migrations.RemoveField(
            model_name='pathology',
            name='skeletal_muscle',
        ),
        migrations.RemoveField(
            model_name='pathology',
            name='visceral_rate',
        ),
        migrations.RemoveField(
            model_name='pathology',
            name='weight',
        ),
        migrations.AddField(
            model_name='vitals',
            name='bmr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='body_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='bone_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='muscle_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='muscle_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='protein_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='protein_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='skeletal_muscle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='visceral_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
