# Generated by Django 5.2.4 on 2025-07-30 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_manager', '0008_identity'),
        ('technician', '0025_rename_bmr_pathology_total_cholesterol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='bmr_pdf',
            field=models.FileField(blank=True, null=True, upload_to='bmr_reports/'),
        ),
        migrations.CreateModel(
            name='SmartReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_pdf', models.FileField(blank=True, null=True, upload_to='smart_reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smart_report', to='camp_manager.patientdata')),
            ],
        ),
    ]
