# Generated by Django 5.2.4 on 2025-08-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0026_vitals_bmr_pdf_smartreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathology',
            old_name='random_blood_sugar',
            new_name='blood_sugar_level',
        ),
        migrations.AddField(
            model_name='pathology',
            name='direct_bilirubin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathology',
            name='hdl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathology',
            name='indirect_bilirubin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathology',
            name='ldl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathology',
            name='lipids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathology',
            name='mch',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathology',
            name='mchc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathology',
            name='mcv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathology',
            name='pcv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathology',
            name='triglycerides',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathology',
            name='vldl',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
