# Generated by Django 5.2.3 on 2025-06-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='service',
            field=models.CharField(max_length=500),
        ),
    ]
