# Generated by Django 5.2.3 on 2025-06-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_manager', '0002_patientdata_checked_in_patientdata_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='pdf_slip',
            field=models.FileField(blank=True, null=True, upload_to='pdf_slips/'),
        ),
    ]
