# Generated by Django 5.2.3 on 2025-07-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_manager', '0003_patientdata_pdf_slip'),
    ]

    operations = [
        migrations.AddField(
            model_name='campmanager',
            name='login_type',
            field=models.CharField(default='Coordinator', max_length=20),
        ),
    ]
