# Generated by Django 5.2.4 on 2025-07-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_manager', '0005_patientdata_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='test_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
