# Generated by Django 5.2.4 on 2025-07-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_manager', '0006_patientdata_test_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='loan_account_number',
            field=models.CharField(blank=True, help_text='10–20 digit loan account number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload patient/employee photo', null=True, upload_to='patient_photos/'),
        ),
    ]
