# Generated by Django 5.2.4 on 2025-07-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp_manager', '0008_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='loan_document_file',
            field=models.FileField(blank=True, help_text='Loan-related document, if provided', null=True, upload_to='loan_documents/'),
        ),
    ]
